### PR TITLE
Move to the updated interface.

### PR DESCRIPTION
**Pull request by jordandukart**
Not sure if this module is still being used/maintained but the interface for Handles is changing in https://github.com/discoverygarden/islandora_handle/pull/32/files so doing some due diligence. 

@lucasvanschaik

### CODE REVIEW

**Review by lucasvanschaik — CHANGES_REQUESTED** [review]
Hi Jordan,
Thanks for the PR. I was not aware of the updated interface.
Is it possible to make it so that it will work with both the old and the new interface?
Something like (not tested):
if (function_exists('islandora_handle_query_for_handle')) {
    $results['HDL']['isavailable'] = islandora_handle_query_for_handle($object);
}
elseif (function_exists('islandora_handle_retrieve_selected_handler')) {
   $handler_class = islandora_handle_retrieve_selected_handler();
   $handler = new $handler_class($object);
   $results['HDL']['isavailable'] = $handler->readHandle($object);
}

**Comment by jordandukart** [comment]
Hey @lucasvanschaik just saw this, the Handle 7 interface is being ported over to this new format as well which I think should suffice? For reference: https://github.com/discoverygarden/islandora_handle/blob/7.x/includes/IslandoraHandleServiceHandler.class.inc

**Comment by jordandukart** [comment]
Bump @lucasvanschaik

**Review by lucasvanschaik — CHANGES_REQUESTED** [review]
Can you change the code so it works with both the old and the new handle module?
Something like:
if (function_exists('islandora_handle_query_for_handle')) {
  $results['HDL']['isavailable'] = islandora_handle_query_for_handle($object);
}
elseif (function_exists('islandora_handle_retrieve_selected_handler')) {
  $handler_class = islandora_handle_retrieve_selected_handler();
  $handler = new $handler_class($object);
  $results['HDL']['isavailable'] = $handler->readHandle($object);
}

**Comment by jordandukart** [comment]
If that's the direction you'd like this to go I can do that now, updated PR coming.

**Comment by lucasvanschaik** [comment]
Thanks, looks good!

**Pull request merged**
